// GENERATED BY CURSOR (strict) — Phase 1 test
import 'package:flutter_test/flutter_test.dart';
import 'package:cdax_app/providers/subscription_provider.dart';

void main() {
  test('UPI regex validates typical ids', () {
    final ctrl = SubscriptionController.instance;
    expect(ctrl.validateUpi('user@icici'), isNull);
    expect(ctrl.validateUpi(''), isNotNull);
    expect(ctrl.validateUpi('bad_id'), isNotNull);
  });
}


