// GENERATED BY CURSOR (strict) — changed Phase 1 on 2025-09-30. ASSUMPTION: Pure mock service.
// TODO_BACKEND: Replace implementations with real API calls; keep method signatures intact.

import 'dart:async';
import 'dart:math';

import '../providers/subscription_provider.dart';

class MockPaymentService {
  static Future<PaymentResult> processUpi({required String upiId, required String plan, String? courseId, String? courseTitle, double? amount}) async {
    await Future.delayed(const Duration(milliseconds: 900));
    final rng = Random();
    final ok = rng.nextBool();
    if (ok) {
      final label = courseTitle != null ? 'course "$courseTitle"' : plan;
      return PaymentResult(success: true, message: 'Payment successful for $label via $upiId');
    }
    return const PaymentResult(success: false, message: 'Payment declined. Please try again.');
  }
}


