// GENERATED BY CURSOR (strict) — changed Phase 1 on 2025-09-30. ASSUMPTION: UPI-only form.

import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';

import '../../providers/subscription_provider.dart';

class PaymentUpiScreen extends StatefulWidget {
  const PaymentUpiScreen({super.key});

  @override
  State<PaymentUpiScreen> createState() => _PaymentUpiScreenState();
}

class _PaymentUpiScreenState extends State<PaymentUpiScreen> {
  final _formKey = GlobalKey<FormState>();
  final _upiCtrl = TextEditingController();
  final sub = SubscriptionController.instance;
  bool _submitting = false;

  @override
  void dispose() {
    _upiCtrl.dispose();
    super.dispose();
  }

  Future<void> _submit() async {
    if (!_formKey.currentState!.validate()) return;
    setState(() => _submitting = true);
    final result = await sub.processUpiPayment(_upiCtrl.text.trim());
    if (!mounted) return;
    setState(() => _submitting = false);
    if (result.success) {
      context.push('/dashboard/subscription/result');
    } else {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text(result.message)),
      );
    }
  }

  @override
  Widget build(BuildContext context) {
    return Material(
      color: const Color.fromARGB(255, 255, 254, 254),
      child: SafeArea(
        child: Padding(
        padding: const EdgeInsets.all(16),
        child: Form(
          key: _formKey,
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Row(
                children: [
                  IconButton(
                    icon: const Icon(Icons.arrow_back),
                    onPressed: () => Navigator.of(context).maybePop(),
                  ),
                  const SizedBox(width: 8),
                  const Text('Enter your UPI ID'),
                ],
              ),
              const SizedBox(height: 12),
              TextFormField(
                controller: _upiCtrl,
                decoration: const InputDecoration(
                  hintText: 'example@bank',
                  prefixIcon: Icon(Icons.account_balance_wallet),
                ),
                validator: sub.validateUpi,
                textInputAction: TextInputAction.done,
                autofillHints: const [AutofillHints.username],
              ),
              const SizedBox(height: 16),
              FilledButton(
                onPressed: _submitting ? null : _submit,
                child: Text(_submitting ? 'Processing...' : 'Proceed to pay'),
              ),
            ],
          ),
        ),
      ),
    ));
  }
}


