// GENERATED BY CURSOR (strict) — changed Phase 1 on 2025-09-30. ASSUMPTION: UPI-only form.

import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';

import '../../providers/subscription_provider.dart';

class PaymentUpiScreen extends StatefulWidget {
  const PaymentUpiScreen({super.key});

  @override
  State<PaymentUpiScreen> createState() => _PaymentUpiScreenState();
}

class _PaymentUpiScreenState extends State<PaymentUpiScreen> {
  final _formKey = GlobalKey<FormState>();
  final _upiCtrl = TextEditingController();
  final sub = SubscriptionController.instance;
  bool _submitting = false;

  @override
  void dispose() {
    _upiCtrl.dispose();
    super.dispose();
  }

  Future<void> _submit() async {
    if (!_formKey.currentState!.validate()) return;
    
    // Validate payment context
    if (sub.selectedAmount == null || sub.selectedAmount! <= 0) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Payment amount not set. Please go back and select a course.')),
      );
      return;
    }
    
    if (sub.selectedCourseId == null || sub.selectedCourseId!.isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Course not selected. Please go back and select a course.')),
      );
      return;
    }
    
    setState(() => _submitting = true);
    
    try {
      await sub.processUpiPayment(
        upiId: _upiCtrl.text.trim(),
        amount: sub.selectedAmount!,
        courseId: sub.selectedCourseId!,
        courseTitle: sub.selectedCourseTitle ?? 'Course',
      );
      
      final result = sub.lastPaymentResult;
      if (!mounted) return;
      
      if (result?.success == true) {
        context.push('/dashboard/subscription/result');
      } else {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text(result?.message ?? 'Payment failed')),
        );
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Payment error: ${e.toString()}')),
        );
      }
    } finally {
      if (mounted) {
        setState(() => _submitting = false);
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Material(
      color: const Color.fromARGB(255, 255, 254, 254),
      child: SafeArea(
        child: Padding(
        padding: const EdgeInsets.all(16),
        child: Form(
          key: _formKey,
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Row(
                children: [
                  IconButton(
                    icon: const Icon(Icons.arrow_back),
                    onPressed: () => Navigator.of(context).maybePop(),
                  ),
                  const SizedBox(width: 8),
                  const Text('Enter your UPI ID'),
                ],
              ),
              const SizedBox(height: 12),
              TextFormField(
                controller: _upiCtrl,
                decoration: const InputDecoration(
                  hintText: 'example@bank',
                  prefixIcon: Icon(Icons.account_balance_wallet),
                ),
                validator: sub.validateUpi,
                textInputAction: TextInputAction.done,
                autofillHints: const [AutofillHints.username],
              ),
              const SizedBox(height: 16),
              FilledButton(
                onPressed: _submitting ? null : _submit,
                child: Text(_submitting ? 'Processing...' : 'Proceed to pay'),
              ),
            ],
          ),
        ),
      ),
    ));
  }
}


