// GENERATED BY CURSOR (strict) — changed Phase 1 on 2025-09-30. ASSUMPTION: Dashboard child page.

import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';

import '../../providers/subscription_provider.dart';

class SubscriptionOverviewScreen extends StatefulWidget {
  const SubscriptionOverviewScreen({super.key});

  @override
  State<SubscriptionOverviewScreen> createState() => _SubscriptionOverviewScreenState();
}

class _SubscriptionOverviewScreenState extends State<SubscriptionOverviewScreen> {
  final sub = SubscriptionController.instance;

  @override
  void initState() {
    super.initState();
    sub.addListener(_onChange);
  }

  @override
  void dispose() {
    sub.removeListener(_onChange);
    super.dispose();
  }

  void _onChange() {
    if (!mounted) return;
    setState(() {});
  }

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    return Material(
      color: const Color.fromARGB(255, 255, 255, 255),
      child: SafeArea(
        child: SingleChildScrollView(
        padding: const EdgeInsets.all(16),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Row(
                children: [
                  IconButton(
                    icon: const Icon(Icons.arrow_back),
                    onPressed: () => Navigator.of(context).maybePop(),
                  ),
                  const SizedBox(width: 8),
                  Text('Your Plan', style: theme.textTheme.titleMedium),
                ],
              ),
            const SizedBox(height: 8),
            Card(
              child: ListTile(
                leading: const Icon(Icons.workspace_premium),
                title: Text(sub.currentPlan),
                subtitle: Text('Status: ${sub.status.name}'),
              ),
            ),
            const SizedBox(height: 16),
            FilledButton(
              onPressed: () => context.push('/dashboard/subscription/methods'),
              child: const Text('Select your plan & pay'),
            ),
          ],
        ),
      ),
    ));
  }
}


